version: '1'
services:
  envoyapigateway: 
    build: Envoy/
    ports: 
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
  service1:
    build: Service1/
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
  service2:
    build: Service2/
    ports:
      - "6000:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
    
  